### ISSUE TITLE
Timeout not working

### ISSUE THREAD

**Issue by 9SL9** [tinuzz/leaflet-messagebox#1]
If I set a timeout of 10 seconds and call box.show within that 10 second timeout the timeout is not reset for each call. e.g. If I call box.show, then after 5 seconds call it again the second box will only show for 5 seconds instead of the full 10

**Comment by tinuzz** [comment]
Ah, this is a use case I hadn't considered. I'll fix it by cancelling any existing timeouts on a call to show(). Just need to find some time for coding and testing.

**Comment by tinuzz** [comment]
Fixed in 6466fbdb3c20b2b7812f6bb30631ea201a6cf9fd
