### ISSUE TITLE
Custom position when using implicit on map creation?

### ISSUE THREAD

**Issue by a1an77** [tinuzz/leaflet-messagebox#2]
Hi, is there a way to customize the control location while using the implicit map option to create it?
I tried with map.messagebox.options = X and  map.messagebox.setPosition(X) unsuccessfully. It seems that once created at topright it will then not move again.

**Comment by tinuzz** [comment]
Hi,

The setPosition() call should work. The demo at https://www.grendelman.net/leaflet/ does exactly that:

```
var options = { messagebox: true };
var map = L.map('map', options);
var positions = [ 'topleft', 'topright', 'bottomleft', 'bottomright' ];
var j = Math.floor(Math.random() * positions.length);
var pos = positions[j];
map.messagebox.setPosition(pos);
```

and that works fine....

**Comment by a1an77** [comment]
I might have used a wrong label to set it then, thanks for checking.
